// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddManualTrade(arg1:backend.Trade):Promise<void>;

export function AutoSyncTick():Promise<void>;

export function CancelGoogleLogin():Promise<void>;

export function FetchFromMT5():Promise<string>;

export function FetchOpenPositions():Promise<Array<backend.OpenPosition>>;

export function GetAutoBackfillEnabled():Promise<boolean>;

export function GetCloudProfile():Promise<backend.CloudProfile>;

export function GetCurrency():Promise<string>;

export function GetDashboardData(arg1:string):Promise<Array<backend.Trade>>;

export function GetEntitlement():Promise<backend.EntitlementView>;

export function GetMT5AccountInfo():Promise<backend.MT5AccountInfo>;

export function GetSyncTarget():Promise<backend.SyncTargetInfo>;

export function IsCloudConnected():Promise<boolean>;

export function LoginWithGoogle():Promise<void>;

export function LogoutCloud():Promise<void>;

export function OpenUpgradePage():Promise<void>;

export function RefreshEntitlement():Promise<void>;

export function SetAutoBackfillEnabled(arg1:boolean):Promise<void>;

export function SetSyncTarget(arg1:string,arg2:string):Promise<void>;

export function SyncOpenPositionsToCloud():Promise<string>;

export function SyncRecentClosedToCloud():Promise<string>;

export function SyncToCloud():Promise<string>;
