// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManualTrade(arg1) {
  return window['go']['main']['App']['AddManualTrade'](arg1);
}

export function AutoSyncTick() {
  return window['go']['main']['App']['AutoSyncTick']();
}

export function CancelGoogleLogin() {
  return window['go']['main']['App']['CancelGoogleLogin']();
}

export function FetchFromMT5() {
  return window['go']['main']['App']['FetchFromMT5']();
}

export function FetchOpenPositions() {
  return window['go']['main']['App']['FetchOpenPositions']();
}

export function GetAutoBackfillEnabled() {
  return window['go']['main']['App']['GetAutoBackfillEnabled']();
}

export function GetCloudProfile() {
  return window['go']['main']['App']['GetCloudProfile']();
}

export function GetCurrency() {
  return window['go']['main']['App']['GetCurrency']();
}

export function GetDashboardData(arg1) {
  return window['go']['main']['App']['GetDashboardData'](arg1);
}

export function GetEntitlement() {
  return window['go']['main']['App']['GetEntitlement']();
}

export function GetMT5AccountInfo() {
  return window['go']['main']['App']['GetMT5AccountInfo']();
}

export function GetSyncTarget() {
  return window['go']['main']['App']['GetSyncTarget']();
}

export function IsCloudConnected() {
  return window['go']['main']['App']['IsCloudConnected']();
}

export function LoginWithGoogle() {
  return window['go']['main']['App']['LoginWithGoogle']();
}

export function LogoutCloud() {
  return window['go']['main']['App']['LogoutCloud']();
}

export function OpenUpgradePage() {
  return window['go']['main']['App']['OpenUpgradePage']();
}

export function RefreshEntitlement() {
  return window['go']['main']['App']['RefreshEntitlement']();
}

export function SetAutoBackfillEnabled(arg1) {
  return window['go']['main']['App']['SetAutoBackfillEnabled'](arg1);
}

export function SetSyncTarget(arg1, arg2) {
  return window['go']['main']['App']['SetSyncTarget'](arg1, arg2);
}

export function SyncOpenPositionsToCloud() {
  return window['go']['main']['App']['SyncOpenPositionsToCloud']();
}

export function SyncRecentClosedToCloud() {
  return window['go']['main']['App']['SyncRecentClosedToCloud']();
}

export function SyncToCloud() {
  return window['go']['main']['App']['SyncToCloud']();
}
